code --install-extension abumalick.vscode-nvm
code --install-extension akamud.vscode-theme-onedark
code --install-extension apollographql.vscode-apollo
code --install-extension attilabuti.vscode-mjml
code --install-extension christian-kohler.path-intellisense
code --install-extension cschleiden.vscode-github-actions
code --install-extension dbaeumer.vscode-eslint
code --install-extension Dedsec727.jekyll-run
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension euskadi31.json-pretty-printer
code --install-extension file-icons.file-icons
code --install-extension ginfuru.ginfuru-vscode-jekyll-syntax
code --install-extension hashicorp.terraform
code --install-extension letrieu.expand-region
code --install-extension mechatroner.rainbow-csv
code --install-extension mrmlnc.vscode-lebab
code --install-extension ms-playwright.playwright
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension normanstypczynskipublisher.gqlformatter
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension redhat.vscode-yaml
code --install-extension shakram02.bash-beautify
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one
